# Generated by Django 5.2.17 on 2026-09-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_certification'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
