# Generated by Django 5.2.17 on 2026-09-14 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_certification_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
