# Generated by Django 5.2.17 on 2026-09-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_certification_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
